#!/usr/bin/env bash
# transfers file from local machine to server using scp

if [ "$#" -lt 3 ]
then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$4" "$1" "$3"@"$2":~/
fi
