#!/usr/bin/env bash
#installs nginx on the server

sudo apt-get -y update
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/default
sudo nginx -s reload
