#!/usr/bin/env bash
#installs nginx on the server

sudo apt-get -y update
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo nginx -s reload
