#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02


sudo apt-get -y update
sudo apt-get -y  install haproxy


# make sure that HAproxy can be managed via an init script
sudo echo "
# set ENABLED to 1 if you want the init script to start haproxy
ENABLED=1" | tee -a /etc/default/haproxy

# configure load balance
sudo echo "
listen www
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 27845-web-01 35.172.230.212:80 check
	server 27845-web-02 3.233.224.164:80 check
" | tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
