#!/usr/bin/env bash
# 

sigint() {
	echo "Y U no love me?!"
	exit 0
}

sigterm() {
	echo "I hate the kill command"
	rm "$file"
	exit 0
}
sigquit() {
	rm "$file"
	exit 0
}

trap sigint SIGINT
trap sigterm SIGTERM
trap sigquit SIGQUIT

file=/var/run/myscript.pid

pgrep -f 100-process_and_pid_file >> $file
x=1
while [ $x -gt 0 ]
do
	echo "To infinity and beyond"
	((x++))
	sleep 2
done
