#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds

x=1
while [ $x -gt 0 ]
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
	((x++))
done
