#!/usr/bin/env bash
# Uses while loop to print "Best School 10 times"

x=1
while [ $x -le 10 ]
do
	if [ $x == 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( x+=1 ))
done
