#!/usr/bin/env bash
# Uses while loop to print "Best School 10 times"

x=1
while [ $x -le 20 ]
do
	case $x in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
		*)
		echo "$x"
		;;
	esac
	
	(( x+=1 ))
done
