#!/usr/bin/env bash
# Runs nginx as nginx user

sed -ni 's/user .*/user nginx/' /etc/nginx/nginx.conf
sed -n 's/^       listen 80/      listen 8080/p' /etc/nginx/sites-enabled/default
sed -n 's/^       listen \[::\]:80/      listen [::]:8080/p' /etc/nginx/sites-enabled/default
